version: 2
machine:
  pre:
    - mkdir ~/.yarn
dependencies:
  cache_directories:
    - ~/.yarn
jobs:
  build:
    docker:
      # specify the version you desire here
      - image: circleci/node:latest-browsers
    working_directory: ~/vialer-js
    steps:
      - checkout
      - restore_cache:
          name: Restore Yarn Package Cache
          keys:
            - npm-packages-v1-{{ checksum "yarn.lock" }}
      - run: yarn --cache-folder ~/.yarn
      - save_cache:
          name: Save Yarn Package Cache
          key: npm-packages-v1-{{ .Branch }}-{{ checksum "yarn.lock" }}
          paths:
            - ~/.yarn-cache
      - run: yarn commitlint-ci
      - run: yarn eslint
      - run: yarn stylelint
      - run: cp .circleci/.vialer-jsrc.ci .vialer-jsrc
      - run: BRAND=vialer yarn test-unit
      - run: BRAND=vialer yarn test-browser

